### ISSUE TITLE
ioquake3 and security?

### ISSUE THREAD

**Issue by vanniekerkalex** [diegoulloao/ioquake3-mac-install#10]
Hi,

I was just wanting to find out about your repo and how it's affected with the news regarding ioquake3 being compromised by crypto miners? 

Source: https://ioquake3.org/news/

> As an initial notice, I want to warn ioquake3 players and server operators that precompiled test builds downloaded from our website may have been compromised. Please do not use or run an ioquake3 test build until we provide new builds for download. This post will be updated and a new notice will be provided on this site. ioquake3 builds compiled from source or provided by distributions should be safe to use so long as they did not redistribute our test build binaries. I have no evidence that the ioquake3 test builds were compromised but I am alerting the community out of an abundance of caution.

Should we be concerned running / installing your repo?

Thanks,
Alex

**Comment by diegoulloao** [comment]
Hi, I remember that advisory but this project was compiled from a non test-build version.

**You can install it without security risks.** Also you can read: https://github.com/diegoulloao/ioquake3-mac-install#information-for-developers
about compilation process.

**Comment by vanniekerkalex** [comment]
Ok, great, thanks. Just thought I'd check with you.

Great work on this repo!! It's much appreciated and works like a charm. I recently downgraded from Catalina to High Sierra for Counter Strike, and your repo installed and runs without a problem :)
