### ISSUE TITLE
Can't get cl_allowdownload to work

### ISSUE THREAD

**Issue by bmsq** [diegoulloao/ioquake3-mac-install#11]
Server is running a custom map and has sv_dlURL configured.  cl_allowdownload works fine when connecting using ioquake for windows but download doesn't appear to work while using cl_allowdownload 1 on Mac Catalina.

Console log shows the map is missing from the baseq3 directory and then throws an error because the map was missing.  On Windows ioquake3 uses cURL to download the map (based on the sv_dlURL set on the server) and successfully loads the map.

Any ideas?

**Comment by diegoulloao** [comment]
Please open issues related to game in the official ioquake3 repository: https://github.com/ioquake/ioq3
This repository is only related to the installation script.

**Comment by bmsq** [comment]
Thanks for the reply. 

Did you build this version yourself? If so, i suspect it's related to the build flags/defines used. 

I'm happy to raise an issue with the ioq3 project but a little more information about how you built your executable would be helpful so I can reproduce the issue.

**Comment by bmsq** [comment]
I was able to reproduce this from source code, closing.
