### ISSUE TITLE
Please rename your repository to anything besides ioquake3 or at least call it unofficial

### ISSUE THREAD

**Issue by NuclearMonster** [diegoulloao/ioquake3-mac-install#12]
Hi, we sometimes hear from users that have issues and use your version of ioquake3. Please mark it as "unofficial" or rename it especially as you are distributing a pirated copy of Quake 3's pak0.pk3 which we do not condone.

**Comment by diegoulloao** [comment]
Hi @NuclearMonster, I'm sorry for the inconvenience. I already putted a box at the top of the repository README making the clarification. Please, feel free to notify me for any other circumstance.
