### ISSUE TITLE
Getting error sh: line 69: cd: __MACOSX: No such file or directory

### ISSUE THREAD

**Issue by QuakeDave** [diegoulloao/ioquake3-mac-install#13]
On a Mid 2010 27" iMac with 10.13.6 I get the error: sh: line 69: cd: __MACOSX: No such file or directory

**Comment by diegoulloao** [comment]
@QuakeDave I did an updated today that is causing the error.
I did revert changes to the last stable version. Now it should install correctly.

I'll be working on the issue with the last compiled version today. When I do, I recommend update your installation.

**Comment by diegoulloao** [comment]
@QuakeDave this branch works for you? https://github.com/diegoulloao/ioquake3-mac-install/tree/dev
Updated version seems to be fixed now.

**Comment by QuakeDave** [comment]
Thank you so much for your efforts! It works perfectly! Now me and my friends can play over the holidays!

Best wishes from Germany and merry Christmas and a happy new year to you and your family!

**Comment by diegoulloao** [comment]
Great @QuakeDave. Have a nice christmas and happy new year !
