### ISSUE TITLE
After 30 min of trying i give up

### ISSUE THREAD

**Issue by elephantjesus** [diegoulloao/ioquake3-mac-install#17]
Please tell me how to run it because i tried everything i know and no result i sound so stupid but it got really annoying

**Comment by diegoulloao** [comment]
1. Open a new terminal window
2. Copy and paste in your terminal the command in the installation step:
```
curl -L git.io/ioq3mac | sh
```
3. Press enter and enjoy the process (can take a couple of minutes)

**Comment by elephantjesus** [comment]
![image](https://user-images.githubusercontent.com/78938432/107761108-80682280-6d33-11eb-9b08-184926555975.png)
this is what happened first time i tried to do it and happend now too

**Comment by elephantjesus** [comment]
Yeah still this conection error atfer 25 mins of trying. It goes sometimes up to downloading the pak0.pk3 i think but most of the times it stopes at downloading ioquake itself

**Comment by diegoulloao** [comment]
I think is not a problem related with this repository. I suggest to search about in order to maybe enable the rules for allow port 443 in iptables (I don't know if is exactly this your problem).

https://stackoverflow.com/a/9354015/11705679
Check the comment down below the answer.
