### ISSUE TITLE
Installed. Now, how to run it?

### ISSUE THREAD

**Issue by alvarotrigo** [diegoulloao/ioquake3-mac-install#18]
I've installed it by running `curl -L git.io/ioq3mac | sh` 

How can I play now?
Couldn't find anything about it on the docs.

**Comment by diegoulloao** [comment]
An application should appear in your Launchpad. If not, check in your applications folder for another folder called ioquake3 with the executable inside.

**Comment by alvarotrigo** [comment]
Yeah found it on Applications/ioquake3
