### ISSUE TITLE
ioquake3fe.app is still flagged as 32-bit application

### ISSUE THREAD

**Issue by Racuevas39** [diegoulloao/ioquake3-mac-install#3]
Hi. I noticed you guys updated the ioquake3-1.36.app to 64-bits which is great for Catalina, and also works great on Mojave. Although, the config app ioquake3fe-1.36.app is still flagged as 32-bits on Mojave. I haven't updated to Catalina yet, many 32-bits without a proper update yet are on my end, but the two new apps you just posted work well on Mojave.

Any ETA for the config app?

Thanks and great work!

**Comment by diegoulloao** [comment]
Hi bro! It is in progress, this is dev branch so when ioquake3fe-1.36.app be compiled as 64-bits this branch will be merged with master.

We are working the problem on this thread: https://github.com/diegoulloao/ioquake3-mac-install/issues/2

I will be very happy if you know how to make the compile for this .app file. All else is working to this point.

Regards.

**Comment by diegoulloao** [comment]
I couldn't find a way to get or compile ioquake3fe-1.36.app file.

Any idea? Is it indispensable?

**Comment by diegoulloao** [comment]
**ioquake3fe-1.36.app was deleted from repository**.

Reason why is it's just a tool but not indispensable for ioquake3 64-bits running.

Hope include it in a closer future.
