### ISSUE TITLE
curl: (35) Unknown SSL protocol error in connection to cdn.playmorepromode.com:443

### ISSUE THREAD

**Issue by rakhmerov** [diegoulloao/ioquake3-mac-install#6]
Hi,

I'm getting this error when trying to install ioquake3 with the provided command:

**************************************************
	Downloading CPMA Map-Pack ...
**************************************************

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:06 --:--:--     0curl: (35) Unknown SSL protocol error in connection to cdn.playmorepromode.com:443

Is there a known solution/workaround?

**Comment by diegoulloao** [comment]
That line correspond to https://github.com/diegoulloao/ioquake3-mac-install/blob/master/install.sh line 194.

```
# CPMA map pack
echo "\n
**************************************************
	Downloading CPMA Map-Pack ...
**************************************************
\n"

curl -L $mappack > cpma-mappack-full.zip
```

Instruction there executed is:

```
curl -L $mappack > cpma-mappack-full.zip
```

Where $mappack variable url https://cdn.playmorepromode.com/files/cpma-mappack-full.zip is directly the url to the mappack zip file on cpma servers declared in line 41 in the same file:

```
declare -r mappack="https://cdn.playmorepromode.com/files/cpma-mappack-full.zip"
```

So literally instruction there executed is:

```
curl -L https://cdn.playmorepromode.com/files/cpma-mappack-full.zip > cpma-mappack-full.zip
```

Instruction that you can try directly con your terminal without error (at least mine and other tested).

I'll try to find more about.
Anything let me know please.

**Comment by diegoulloao** [comment]
> Hi,
> 
> I'm getting this error when trying to install ioquake3 with the provided command:

What macOS version are you using?

What happend if you run the command below directly on your terminal?
```
curl -L https://cdn.playmorepromode.com/files/cpma-mappack-full.zip > cpma-mappack-full.zip
```

And if previous command fails, what happend if you run this new command below?

```
curl -L --tlsv1 https://cdn.playmorepromode.com/files/cpma-mappack-full.zip > mappack.zip
```

Regards.

**Comment by rakhmerov** [comment]
Hi, thanks for paying attention to this issue.

My macOS version is: 10.15.1

As far as commands:

$ curl -L https://cdn.playmorepromode.com/files/cpma-mappack-full.zip > cpma-mappack-full.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0curl: (35) Unknown SSL protocol error in connection to cdn.playmorepromode.com:443


$ curl -L --tlsv1 https://cdn.playmorepromode.com/files/cpma-mappack-full.zip > mappack.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0curl: (35) Unknown SSL protocol error in connection to cdn.playmorepromode.com:443

Maybe I'm missing some ssl-related library on my mac. I'll try to find out.

I just updated it and my previous ioquake3 app stopped working because it's considered legacy now (32 bit).

The interesting thing is that using your simple command it is still able to download the "app" file under "ioquake3" folder under Applications. If I run this app then my Q3 works but I can't find a screen resolution to play in full screen normally. My mac is 15'', previously I set it to 1024x768 and it would open in full screen normally. But now If I do the same I see only part of the content on the screen. It's shifted much to the top. Another issue is that the textures are weird, not so beautiful as they were before.

**Comment by rakhmerov** [comment]
Just FYI: I just commented out those two downloads, manipulated with config a little bit (specifically I set "r_mode" to "-2" so that it fits well to my 15'' screen) and it now works as a norma Q3 w/o any specific modifications (textures, sounds etc.). So your script helped anyway :)

Thanks

**Comment by diegoulloao** [comment]
Perfect. If you find a solution for "curl: (35) Unknown SSL protocol error in connection to cdn.playmorepromode.com:443", please notify me to prevent this for other users.

Regards.

**Comment by rakhmerov** [comment]
Ok

Thanks

Renat Akhmerov
@Nokia
9 нояб. 2019 г., 01:14 +0700, Diego Ulloa <notifications@github.com>, писал:
