### ISSUE TITLE
Defrag mode

### ISSUE THREAD

**Issue by bashmentarium** [diegoulloao/ioquake3-mac-install#8]
I remember from the old days I used to play defrag mode maps and it was very challenging, besides the fact that every map in that mode shipped with a couple of demos of pro's smashing the living crap out of that maps in record timings, I would love this mode to be a part of quake gameplay.

**Comment by diegoulloao** [comment]
Perfect. Let me see what can I do.
¿Where the mods files are?

**Comment by bashmentarium** [comment]
I found a Defrag complete pack on - https://www.moddb.com/mods/defrag/downloads/defrag-installer.

**Comment by diegoulloao** [comment]
Perfect. This is not an issue so i'll close it.
I'll take a look thanks for suggestion.

**Comment by diegoulloao** [comment]
Hi, I figured out defrag mod installation is very simple, you only have to **download the complete pack files** from [here](https://www.moddb.com/mods/defrag/downloads/defrag-installer) **and then copy them to:**

> ~/Library/Application Support/Quake3

**directory.**

**For open** this directory quickly you can simply run:
```
open ~/Library/Application\ Support/Quake3
```

**Files required are:**
- defrag folder
- all except default pak.pk3 files in baseq3

**Comment by diegoulloao** [comment]
Also I added readme instructions (91e37f0) to extend the game, for example: defrag mode.

**Comment by bashmentarium** [comment]
> Hi, I figured out defrag mod installation is very simple, you only have to **download the complete pack files** from [here](https://www.moddb.com/downloads/mirror/130690/122/1ca648c6799a8f03a6876fd4ad333e39/?referer=https%3A%2F%2Fwww.moddb.com%2Fmods%2Fdefrag) **and then copy them to:**

I am sorry for sleeping on this one, but the mirror download link has expired :(

However, I would suggest the link to download the complete Defrag pack should be this one - [defrag-installer](https://www.moddb.com/mods/defrag/downloads/defrag-installer)

**Comment by diegoulloao** [comment]
Link updated.
