### ISSUE TITLE
The player doesn't run/walk forward

### ISSUE THREAD

**Issue by bashmentarium** [diegoulloao/ioquake3-mac-install#9]
Whatever key I bind for the run/walk command, I just don't  move forward. I've quickly started a new game as soon as I installed, chose a map, added a bot and... it doesn't move forward. Left, right, jump, crouches, shoot - everything is alright. I've restarted numerous times both the game and the computer. Re-installed it a couple of times. I've also tried binding a ton of other keys to see maybe something is wrong with my keyboard. Everything is fine. It may seem like a joke, but as far as you can see, I've got plenty of "w", "e", "r", "t" so you know my keyboard actually works.

**Comment by diegoulloao** [comment]
Hi. This project is only related with ioquake3 installation script itself, not with base-code programming. You can notify this issue to ioquake3 developers directly at this link: https://github.com/ioquake/ioq3/issues

Once fixed on the official repository I can recompile that source-code for launch a new fixed version here.

Thanks! I would appreciate you keeping me informed.
